version: '3.7'version: '3.7'

services:
  unalmeet_adminuser_db:
    image: mysql:5.7
    ports:
    - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: admin_user
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: unalmeet
    networks:
      - meetnet

  unalmeet_adminuser_ms:  
    build: .
    ports:
    - 4040:80
    restart: always
    entrypoint: sh -c "sleep 60 && php /var/www/laravel_docker/artisan migrate && apache2-foreground"
    networks:
      - meetnet

networks: 
  meetnet: 
      name: meet-network
